BI_project:
  outputs:
    dev:
      dbname: ods_db
      host: localhost
      pass: admin123
      port: 5433
      schema: schema.yml
      threads: 1
      type: postgres
      user: postgres
  target: dev
